application:
  name: otp

server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://db:5432/otp
    # url: jdbc:postgresql://localhost:5432/otp для запуска вне контейнера
    username: user
    password: password

jwt:
  secret: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fbkJ398f"
  expiration: 3600000000
